export const ACHIEVEMENT_SCHEMA_VERSION = 1

const definitions = [
  {
    id: 'onboarding_complete',
    category: 'foundation',
    displayOrder: 10,
    metric: 'profile.onboardingCompleted',
    target: 1,
  },
  {
    id: 'dna_ready',
    category: 'foundation',
    displayOrder: 20,
    metric: 'dna.ready',
    target: 1,
  },
  {
    id: 'rating_1',
    category: 'ratings',
    displayOrder: 100,
    metric: 'ratings.total',
    target: 1,
  },
  {
    id: 'rating_10',
    category: 'ratings',
    displayOrder: 110,
    metric: 'ratings.total',
    target: 10,
  },
  {
    id: 'rating_25',
    category: 'ratings',
    displayOrder: 120,
    metric: 'ratings.total',
    target: 25,
  },
  {
    id: 'rating_50',
    category: 'ratings',
    displayOrder: 130,
    metric: 'ratings.total',
    target: 50,
  },
  {
    id: 'rating_100',
    category: 'ratings',
    displayOrder: 140,
    metric: 'ratings.total',
    target: 100,
  },
  {
    id: 'rating_250',
    category: 'ratings',
    displayOrder: 150,
    metric: 'ratings.total',
    target: 250,
  },
  {
    id: 'rating_500',
    category: 'ratings',
    displayOrder: 160,
    metric: 'ratings.total',
    target: 500,
  },
  {
    id: 'watched_1',
    category: 'watched',
    displayOrder: 200,
    metric: 'watched.total',
    target: 1,
  },
  {
    id: 'watched_10',
    category: 'watched',
    displayOrder: 210,
    metric: 'watched.total',
    target: 10,
  },
  {
    id: 'watched_25',
    category: 'watched',
    displayOrder: 220,
    metric: 'watched.total',
    target: 25,
  },
  {
    id: 'watched_50',
    category: 'watched',
    displayOrder: 230,
    metric: 'watched.total',
    target: 50,
  },
  {
    id: 'watched_100',
    category: 'watched',
    displayOrder: 240,
    metric: 'watched.total',
    target: 100,
  },
  {
    id: 'watched_250',
    category: 'watched',
    displayOrder: 250,
    metric: 'watched.total',
    target: 250,
  },
  {
    id: 'watched_500',
    category: 'watched',
    displayOrder: 260,
    metric: 'watched.total',
    target: 500,
  },
  {
    id: 'movies_10',
    category: 'watched',
    displayOrder: 300,
    metric: 'watched.movies',
    target: 10,
  },
  {
    id: 'movies_50',
    category: 'watched',
    displayOrder: 310,
    metric: 'watched.movies',
    target: 50,
  },
  {
    id: 'movies_100',
    category: 'watched',
    displayOrder: 312,
    metric: 'watched.movies',
    target: 100,
  },
  {
    id: 'movies_250',
    category: 'watched',
    displayOrder: 314,
    metric: 'watched.movies',
    target: 250,
  },
  {
    id: 'tv_10',
    category: 'watched',
    displayOrder: 320,
    metric: 'watched.tv',
    target: 10,
  },
  {
    id: 'tv_50',
    category: 'watched',
    displayOrder: 330,
    metric: 'watched.tv',
    target: 50,
  },
  {
    id: 'tv_100',
    category: 'watched',
    displayOrder: 340,
    metric: 'watched.tv',
    target: 100,
  },
  {
    id: 'tv_250',
    category: 'watched',
    displayOrder: 350,
    metric: 'watched.tv',
    target: 250,
  },
  {
    id: 'favorite_1',
    category: 'favorites',
    displayOrder: 400,
    metric: 'favorites.total',
    target: 1,
  },
  {
    id: 'favorite_10',
    category: 'favorites',
    displayOrder: 410,
    metric: 'favorites.total',
    target: 10,
  },
  {
    id: 'favorite_25',
    category: 'favorites',
    displayOrder: 420,
    metric: 'favorites.total',
    target: 25,
  },
  {
    id: 'favorite_50',
    category: 'favorites',
    displayOrder: 430,
    metric: 'favorites.total',
    target: 50,
  },
  {
    id: 'favorite_100',
    category: 'favorites',
    displayOrder: 440,
    metric: 'favorites.total',
    target: 100,
  },
  {
    id: 'genres_5',
    category: 'variety',
    displayOrder: 500,
    metric: 'watched.distinctGenres',
    target: 5,
  },
  {
    id: 'genres_10',
    category: 'variety',
    displayOrder: 510,
    metric: 'watched.distinctGenres',
    target: 10,
  },
  {
    id: 'genres_15',
    category: 'variety',
    displayOrder: 515,
    metric: 'watched.distinctGenres',
    target: 15,
  },
  {
    id: 'decades_3',
    category: 'variety',
    displayOrder: 520,
    metric: 'watched.distinctDecades',
    target: 3,
  },
  {
    id: 'decades_5',
    category: 'variety',
    displayOrder: 530,
    metric: 'watched.distinctDecades',
    target: 5,
  },
  {
    id: 'decades_7',
    category: 'variety',
    displayOrder: 535,
    metric: 'watched.distinctDecades',
    target: 7,
  },
  {
    id: 'countries_3',
    category: 'variety',
    displayOrder: 540,
    metric: 'watched.distinctCountries',
    target: 3,
  },
  {
    id: 'countries_5',
    category: 'variety',
    displayOrder: 550,
    metric: 'watched.distinctCountries',
    target: 5,
  },
  {
    id: 'countries_10',
    category: 'variety',
    displayOrder: 560,
    metric: 'watched.distinctCountries',
    target: 10,
  },
  {
    id: 'countries_20',
    category: 'variety',
    displayOrder: 570,
    metric: 'watched.distinctCountries',
    target: 20,
  },
  {
    id: 'horror_10',
    category: 'genres',
    displayOrder: 600,
    metric: 'watched.byGenre.27',
    target: 10,
  },
  {
    id: 'horror_25',
    category: 'genres',
    displayOrder: 601,
    metric: 'watched.byGenre.27',
    target: 25,
  },
  {
    id: 'horror_50',
    category: 'genres',
    displayOrder: 602,
    metric: 'watched.byGenre.27',
    target: 50,
  },
  {
    id: 'comedy_10',
    category: 'genres',
    displayOrder: 610,
    metric: 'watched.byGenre.35',
    target: 10,
  },
  {
    id: 'comedy_25',
    category: 'genres',
    displayOrder: 611,
    metric: 'watched.byGenre.35',
    target: 25,
  },
  {
    id: 'comedy_50',
    category: 'genres',
    displayOrder: 612,
    metric: 'watched.byGenre.35',
    target: 50,
  },
  {
    id: 'scifi_10',
    category: 'genres',
    displayOrder: 620,
    metric: 'watched.byGenre.878',
    target: 10,
  },
  {
    id: 'scifi_25',
    category: 'genres',
    displayOrder: 621,
    metric: 'watched.byGenre.878',
    target: 25,
  },
  {
    id: 'scifi_50',
    category: 'genres',
    displayOrder: 622,
    metric: 'watched.byGenre.878',
    target: 50,
  },
  {
    id: 'romance_10',
    category: 'genres',
    displayOrder: 630,
    metric: 'watched.byGenre.10749',
    target: 10,
  },
  {
    id: 'romance_25',
    category: 'genres',
    displayOrder: 631,
    metric: 'watched.byGenre.10749',
    target: 25,
  },
  {
    id: 'romance_50',
    category: 'genres',
    displayOrder: 632,
    metric: 'watched.byGenre.10749',
    target: 50,
  },
  {
    id: 'friend_1',
    category: 'social',
    displayOrder: 700,
    metric: 'friends.accepted',
    target: 1,
  },
  {
    id: 'friends_5',
    category: 'social',
    displayOrder: 710,
    metric: 'friends.accepted',
    target: 5,
  },
  {
    id: 'friends_10',
    category: 'social',
    displayOrder: 720,
    metric: 'friends.accepted',
    target: 10,
  },
  {
    id: 'friends_25',
    category: 'social',
    displayOrder: 730,
    metric: 'friends.accepted',
    target: 25,
  },
  {
    id: 'friends_50',
    category: 'social',
    displayOrder: 740,
    metric: 'friends.accepted',
    target: 50,
  },
  {
    id: 'auteur_devotee',
    category: 'legendary',
    displayOrder: 800,
    metric: 'watched.maxDirectorTitles',
    target: 15,
  },
  {
    id: 'familiar_face',
    category: 'legendary',
    displayOrder: 810,
    metric: 'watched.maxActorTitles',
    target: 25,
  },
  {
    id: 'film_archaeologist',
    category: 'legendary',
    displayOrder: 820,
    metric: 'watched.pre1970',
    target: 25,
  },
  {
    id: 'genre_historian',
    category: 'legendary',
    displayOrder: 830,
    metric: 'watched.maxGenreDecades',
    target: 5,
  },
  {
    id: 'world_cinema_scholar',
    category: 'legendary',
    displayOrder: 840,
    metric: 'watched.worldCinemaScholar',
    target: 1,
  },
  {
    id: 'genre_omnivore',
    category: 'legendary',
    displayOrder: 850,
    metric: 'watched.genresWith10',
    target: 10,
  },
  {
    id: 'generations_of_cinema',
    category: 'legendary',
    displayOrder: 860,
    metric: 'watched.decadesWith10',
    target: 6,
  },
  {
    id: 'long_road',
    category: 'legendary',
    displayOrder: 870,
    metric: 'milestones.longRoad',
    target: 1,
  },
  {
    id: 'secret_director_journey',
    category: 'secret',
    displayOrder: 900,
    metric: 'watched.directorJourney',
    target: 1,
    secret: true,
  },
  {
    id: 'secret_actor_eras',
    category: 'secret',
    displayOrder: 910,
    metric: 'watched.actorEras',
    target: 1,
    secret: true,
  },
  {
    id: 'secret_franchise_marathon',
    category: 'secret',
    displayOrder: 920,
    metric: 'watched.maxCollectionTitles',
    target: 5,
    secret: true,
  },
  {
    id: 'secret_century_club',
    category: 'secret',
    displayOrder: 930,
    metric: 'watched.distinctDecades',
    target: 10,
    secret: true,
  },
  {
    id: 'secret_global_nomad',
    category: 'secret',
    displayOrder: 940,
    metric: 'watched.globalNomad',
    target: 1,
    secret: true,
  },
  {
    id: 'secret_genre_timecapsule',
    category: 'secret',
    displayOrder: 950,
    metric: 'watched.maxGenreDecades',
    target: 7,
    secret: true,
  },
]

export const ACHIEVEMENT_DEFINITIONS = Object.freeze(
  definitions.map(
    definition => Object.freeze({
      ...definition,
    }),
  ),
)

export const ACHIEVEMENT_DEFINITION_BY_ID =
  Object.freeze(
    Object.fromEntries(
      ACHIEVEMENT_DEFINITIONS.map(
        definition => [
          definition.id,
          definition,
        ],
      ),
    ),
  )
