import test from 'node:test'
import assert from 'node:assert/strict'
import { createCommentService } from '../../src/features/comments/services/createCommentService.js'
import { normalizeComment, normalizeComments } from '../../src/features/comments/services/normalizeComment.js'
import { CommentError, toCommentError } from '../../src/features/comments/services/commentErrors.js'
import { commentIdentity, validateCommentInput, validateCommentProfile } from '../../src/features/comments/validation/commentValidation.js'
import { createLibraryAction } from '../../src/features/library/services/libraryAction.js'
const uid = 'fictional-comment-author'
const time = (seconds = 10, nanoseconds = 0) => ({ seconds, nanoseconds, toMillis: () => seconds * 1000 })
const media = { mediaType: 'movie', tmdbId: 123 }
const profile = () => ({ id: uid, username: 'fictional_viewer', displayName: 'Fictional Viewer', photoURL: null, bio: '', onboardingCompleted: true, createdAt: time(), updatedAt: time() })
const input = { text: 'A fictional comment\nwith a second line.', containsSpoiler: false }
const raw = (patch = {}) => ({ ...media, authorUsername: 'fictional_viewer', authorDisplayName: 'Fictional Viewer', ...input, createdAt: time(), updatedAt: time(20), ...patch })
const snap = (data, id = uid, metadata = {}) => ({ id, exists: () => data !== undefined, data: () => data, metadata: { fromCache: false, hasPendingWrites: false, ...metadata } })
function fixture() {
  const auth = { currentUser: { uid } }, store = new Map([['users/'+uid, profile()]]), listeners = [], calls = [], writes = []
  const state = { beforeGet: null, beforeCommit: null, fail: null }
  const deps = {
    auth, db: {}, doc: (...parts) => parts.slice(1).join('/'), collection: (...parts) => ({ path: parts.slice(1).join('/') }),
    orderBy: (...args) => ({ orderBy: args }), limit: value => ({ limit: value }), query: (target, ...constraints) => ({ ...target, constraints }),
    serverTimestamp: () => time(30),
    onSnapshot: (target, options, next, error) => { calls.push(target); const l = { target, options, next, error, stopped: false }; listeners.push(l); return () => { l.stopped = true } },
    runTransaction: async (_, callback) => {
      if (state.fail) throw state.fail
      const pending = []
      await callback({ get: async target => { calls.push(target); await state.beforeGet?.(target); return snap(store.get(target), target.split('/').at(-1)) }, set: (target, data) => pending.push(['set', target, data]), update: (target, data) => pending.push(['update', target, data]), delete: target => pending.push(['delete', target]) })
      await state.beforeCommit?.()
      for (const [op, target, data] of pending) { writes.push([op, target, data]); if (op === 'delete') store.delete(target); else store.set(target, op === 'update' ? { ...store.get(target), ...data } : data) }
    },
  }
  return { service: createCommentService(deps), auth, store, listeners, calls, writes, state }
}
const path = `mediaComments/movie_123/comments/${uid}`
for (const type of ['movie', 'tv']) test(`comment identity ${type}`, () => assert.equal(commentIdentity({ mediaType: type, tmdbId: 123 }).key, `${type}_123`))
for (const value of [null, {}, {mediaType:'person',tmdbId:1}, {mediaType:'movie',tmdbId:'1'}, {mediaType:'movie',tmdbId:0}, {mediaType:'tv',tmdbId:1.5}]) test(`invalid media ${JSON.stringify(value)}`, () => assert.throws(() => commentIdentity(value), {code:'invalid-media'}))
for (const text of ['', ' \n\t ', 'x'.repeat(2001), null, 10]) test(`invalid text ${String(text).length}/${typeof text}`, () => assert.throws(() => validateCommentInput({text,containsSpoiler:false}), {code:'invalid-text'}))
test('trim preserves inner newlines and 2000 boundary', () => { assert.equal(validateCommentInput({...input,text:'  a\nb \n'}).text,'a\nb'); assert.equal(validateCommentInput({...input,text:'x'.repeat(2000)}).text.length,2000) })
for (const containsSpoiler of [undefined, 'true', 0, null]) test(`spoiler must be boolean ${containsSpoiler}`, () => assert.throws(() => validateCommentInput({...input,containsSpoiler}), {code:'invalid-spoiler'}))
test('explicit true spoiler', () => assert.equal(validateCommentInput({...input,containsSpoiler:true}).containsSpoiler,true))
test('valid normalization is detached and preserves text as text', () => { const data=raw({text:'<img src=x>\nhello'}), before={...data};const result=normalizeComment(snap(data),media);assert.deepEqual(data,before);assert.equal(result.text,data.text);assert.deepEqual(result.updatedAt,{seconds:20,nanoseconds:0});assert.equal(result.id,uid) })
for (const patch of [{extra:1},{text:''},{text:'x'.repeat(2001)},{authorUsername:'Bad User'},{authorDisplayName:''},{containsSpoiler:1},{createdAt:null},{updatedAt:{seconds:1,nanoseconds:0}},{updatedAt:time(10,1e9)}]) test(`corrupt comment ${Object.keys(patch)}/${JSON.stringify(patch).length}`, () => assert.throws(() => normalizeComment(snap(raw(patch)),media),{code:'invalid-data'}))
for (const field of Object.keys(raw())) test(`missing comment field ${field}`, () => {const data=raw();delete data[field];assert.throws(()=>normalizeComment(snap(data),media))})
test('identity mismatch refused',()=>assert.throws(()=>normalizeComment(snap(raw({tmdbId:456})),media),{code:'identity-mismatch'}))
test('list filters malformed, sorts timestamp nanoseconds, bounds 20',()=>{const docs=[snap(raw({updatedAt:time(10,1)}),'older'),snap(raw({updatedAt:time(10,2)}),'newer'),snap(raw({text:''}))];assert.deepEqual(normalizeComments({docs},media).map(x=>x.id),['newer','older']);assert.equal(normalizeComments({docs:Array.from({length:25},(_,i)=>snap(raw(),`synthetic-${i}`))},media).length,20)})
for (const patch of [{id:'other-fictional-owner'},{username:'bad name'},{displayName:''},{onboardingCompleted:false},{onboardingCompleted:'true'},{createdAt:null},{photoURL:3},{bio:3}]) test(`invalid profile ${Object.keys(patch)}`,()=>assert.throws(()=>validateCommentProfile(uid,{...profile(),...patch}),{code:'profile'}))
test('public query bounded and ordered, with no Auth user',()=>{const f=fixture();f.auth.currentUser=null;const stop=f.service.subscribeToMediaComments(media,{next(){},error:assert.fail});assert.deepEqual(f.calls,[{path:'mediaComments/movie_123/comments',constraints:[{orderBy:['updatedAt','desc']},{limit:20}]}]);stop();assert.equal(f.listeners[0].stopped,true)})
for(const guest of [null,undefined,'', 'other-fictional-owner']) test(`own subscription denies ${guest}`,()=>{const f=fixture();if(guest===null)f.auth.currentUser=null;let error;f.service.subscribeToOwnComment(guest,media,{next:assert.fail,error:e=>error=e});assert.equal(error.code,'unauthenticated');assert.equal(f.calls.length,0)})
test('own exact doc, missing result, unsubscribe ignores stale success/error',()=>{const f=fixture(), seen=[], errors=[];const stop=f.service.subscribeToOwnComment(uid,media,{next:x=>seen.push(x),error:x=>errors.push(x)});assert.equal(f.calls[0],path);f.listeners[0].next(snap(undefined));assert.deepEqual(seen,[null]);stop();f.listeners[0].next(snap(raw()));f.listeners[0].error({code:'unavailable'});assert.equal(seen.length,1);assert.equal(errors.length,0)})
test('public and own ignore cache/pending snapshots',()=>{for(const own of [false,true]){const f=fixture(),seen=[];const cb={next:x=>seen.push(x),error:assert.fail};if(own)f.service.subscribeToOwnComment(uid,media,cb);else f.service.subscribeToMediaComments(media,cb);const emit=metadata=>f.listeners[0].next(own?snap(raw(),uid,metadata):{docs:[snap(raw())],metadata});emit({fromCache:false,hasPendingWrites:false});emit({fromCache:true});emit({hasPendingWrites:true});assert.equal(seen.length,1)}})
test('corrupt direct read error; public skips document',()=>{const f=fixture();let error,result;f.service.subscribeToOwnComment(uid,media,{next:assert.fail,error:e=>error=e});f.listeners[0].next(snap(raw({text:''})));assert.equal(error.code,'invalid-data');f.service.subscribeToMediaComments(media,{next:x=>result=x,error:assert.fail});f.listeners[1].next({docs:[snap(raw({text:''}))],metadata:{}});assert.deepEqual(result,[])})
for(const type of ['movie','tv'])test(`transaction creates ${type} exact schema/timestamps`,async()=>{const f=fixture();await f.service.saveComment(uid,profile(),{...media,mediaType:type},{...input,text:'  hello\nworld  '});const [op,target,data]=f.writes[0];assert.equal(op,'set');assert.equal(target,`mediaComments/${type}_123/comments/${uid}`);assert.deepEqual(Object.keys(data).sort(),Object.keys(raw()).sort());assert.equal(data.text,'hello\nworld');assert.equal(data.createdAt.toMillis(),30000);assert.equal(data.updatedAt.toMillis(),30000);assert.deepEqual(f.calls.slice(0,1),['users/'+uid])})
test('edit only text/spoiler/updatedAt preserving old author snapshot',async()=>{const f=fixture();const old=raw({authorDisplayName:'Earlier Name',authorUsername:'earlier_name'});f.store.set(path,old);await f.service.saveComment(uid,profile(),media,{text:'Updated',containsSpoiler:true});assert.deepEqual(Object.keys(f.writes[0][2]).sort(),['containsSpoiler','text','updatedAt']);assert.equal(f.store.get(path).createdAt,old.createdAt);assert.equal(f.store.get(path).authorDisplayName,'Earlier Name')})
test('delete idempotent and never touches ratings or library',async()=>{const f=fixture();f.store.set(path,raw());f.store.set('users/'+uid+'/ratings/movie_123',{score:5});const before=new Map(f.store);await f.service.deleteComment(uid,media);await f.service.deleteComment(uid,media);assert.equal(f.writes.length,1);assert.equal(f.writes[0][0],'delete');before.delete(path);assert.deepEqual(f.store,before);assert.ok(f.calls.every(p=>!p.includes('savedMedia')&&!p.includes('/ratings/')))})
for(const operation of ['save','delete'])test(`${operation} denies incomplete current profile`,async()=>{const f=fixture();f.store.set('users/'+uid,{...profile(),onboardingCompleted:false});await assert.rejects(operation==='save'?f.service.saveComment(uid,profile(),media,input):f.service.deleteComment(uid,media),{code:'profile'});assert.equal(f.writes.length,0)})
test('profile mismatch rejected before Firestore',async()=>{const f=fixture();await assert.rejects(f.service.saveComment(uid,{...profile(),id:'other'},media,input),{code:'profile'});assert.equal(f.calls.length,0)})
test('stale supplied author snapshot rejected',async()=>{const f=fixture();await assert.rejects(f.service.saveComment(uid,{...profile(),displayName:'Wrong name'},media,input),{code:'profile'});assert.equal(f.writes.length,0)})
test('invalid input and media before Firestore',async()=>{const f=fixture();await assert.rejects(f.service.saveComment(uid,profile(),media,{...input,text:''}));await assert.rejects(f.service.saveComment(uid,profile(),{mediaType:'person',tmdbId:1},input));assert.equal(f.calls.length,0)})
test('incompatible existing identity blocks edit and delete',async()=>{const f=fixture();f.store.set(path,raw({tmdbId:456}));await assert.rejects(f.service.saveComment(uid,profile(),media,input),{code:'identity-mismatch'});await assert.rejects(f.service.deleteComment(uid,media),{code:'identity-mismatch'});assert.equal(f.writes.length,0)})
test('logout before read completion blocks write',async()=>{const f=fixture();f.state.beforeGet=()=>{f.auth.currentUser=null};await assert.rejects(f.service.saveComment(uid,profile(),media,input));assert.equal(f.writes.length,0)})
test('same uid replaced session rejected',async()=>{const f=fixture();f.state.beforeGet=()=>{f.auth.currentUser={uid}};await assert.rejects(f.service.saveComment(uid,profile(),media,input),{code:'session'});assert.equal(f.writes.length,0)})
test('already dispatched commit may succeed but never returns success after logout',async()=>{const f=fixture();f.state.beforeCommit=()=>{f.auth.currentUser=null};await assert.rejects(f.service.saveComment(uid,profile(),media,input));assert.equal(f.writes.length,1)})
test('own callback cannot deliver data after session change',()=>{const f=fixture(),seen=[];let error;f.service.subscribeToOwnComment(uid,media,{next:x=>seen.push(x),error:x=>error=x});f.auth.currentUser={uid};f.listeners[0].next(snap(raw()));assert.equal(seen.length,0);assert.equal(error.code,'session')})
test('double action lock, pending query removal held, fresh reattachment only',async()=>{const f=fixture(),seen=[];f.service.subscribeToMediaComments(media,{next:x=>seen.push(x),error:assert.fail});let release;f.state.beforeCommit=()=>new Promise(resolve=>{release=resolve});const work=f.service.saveComment(uid,profile(),media,input);await new Promise(r=>setImmediate(r));await assert.rejects(f.service.deleteComment(uid,media),{code:'pending'});f.listeners[0].next({docs:[],metadata:{hasPendingWrites:false}});assert.equal(seen.length,0);release();await work;assert.equal(f.listeners[0].stopped,true);f.listeners[0].next({docs:[],metadata:{}});assert.equal(seen.length,0);f.listeners[1].next({docs:[snap(raw())],metadata:{}});assert.equal(seen.length,1)})
test('read reconnect never repeats failed mutation',async()=>{const f=fixture();f.service.subscribeToMediaComments(media,{next(){},error(){}});f.state.fail={code:'unavailable',message:'PRIVATE'};await assert.rejects(f.service.saveComment(uid,profile(),media,input),{code:'unavailable'});assert.equal(f.writes.length,0);assert.equal(f.listeners.length,2)})
for(const code of ['permission-denied','firestore/permission-denied','unauthenticated','unavailable','deadline-exceeded','network-request-failed','aborted','cancelled','private-unknown'])test(`safe comment error ${code}`,()=>{const error=toCommentError({code,message:'PRIVATE DATA'});assert.ok(error instanceof CommentError);assert.ok(!error.message.includes('PRIVATE'));assert.notEqual(error.message,code)})
test('controller double submit and disposed callback protection',async()=>{const c=createLibraryAction();c.activate();let release,calls=0,success=0;const run=()=>c.run(()=>{calls++;return new Promise(r=>release=r)},()=>{},()=>success++);const p=run();await run();assert.equal(calls,1);c.dispose();release();await p;assert.equal(success,0)})

for (const error of [null, undefined, 'raw failure', {code:42}, {code:{}}]) test(`unknown error shape ${typeof error}/${JSON.stringify(error)}`, () => assert.equal(toCommentError(error).code, 'unknown'))
for (const code of ['invalid-argument', 'data-loss']) test(`invalid data mapping ${code}`, () => assert.equal(toCommentError({code}).code, 'invalid-data'))
